quotes_site/app_quotes/urls.py
from django.urls import path

from . import views

app_name = "app_quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="main_paginate"),
    path("author/<str:author_name>", views.about_author, name="about_author"),
    path("quote/", views.quote, name="quote"),
    path("add-author/", views.author, name="author"),
]

quotes_site/quotes_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_quotes.urls')),
    path('users/', include('users.urls')),
]

quotes_site/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView



from . import views


app_name = "users"

urlpatterns = [
   
    path("signup/", RegisterView.as_view(), name="signup"),
    path("login/", views.login_user, name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
 ]

quotes_site/app_quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

quotes_site/app_quotes/forms.py
from django.forms import ModelForm, CharField, TextInput

from .models import Quote, Author


class QuoteForm(ModelForm):
    quote = CharField()

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50)
    born_location = CharField(max_length=150)
    description = CharField()

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]

quotes_site/app_quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .forms import QuoteForm, AuthorForm
from .models import Tag, Quote, Author

def main(request, page=1):
    per_page = 10
    quotes = Quote.objects.all()
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "app_quotes/index.html", context={'quotes': quotes_on_page})


def about_author(request, author_name):
    author = get_object_or_404(Author, fullname=author_name)
    return render(request, "app_quotes/about_author.html", context={"author": author})

@login_required
def quote(request):
    tags = Tag.objects.all()
    all_authors = Author.objects.all()
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            new_quote.author = Author.objects.get(id=request.POST.get("author"))
            new_quote.save()

            return redirect(to="app_quotes:main")
        else:
            return render(
                request,
                "app_quotes/quote.html",
                {"tags": tags, "all_authors": all_authors, "form": form},
            )

    return render(
        request,
        "app_quotes/quote.html",
        {"tags": tags, "all_authors": all_authors, "form": QuoteForm()},
    )


@login_required
def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            new_author.save()

            return redirect(to="app_quotes:main")
        else:
            return render(
                request,
                "app_quotes/author.html",
                {"form": form},
            )

    return render(
        request,
        "app_quotes/author.html",
        {"form": AuthorForm()},
    )

quotes_site/app_quotes/templates/app_quotes/about_author.html
{% extends "app_quotes/base.html" %} {% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

{% endblock %}

quotes_site/app_quotes/templates/app_quotes/author.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1 class="text mb-3"> Adding author</h1>
<form method="POST" action="{% url 'app_quotes:author' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text">
                <strong>Fullname:</strong>
            </label>
        
            <!-- <div class="col mb-3"> -->
            <div>{{ form.fullname }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text">
                <strong>Born date:</strong>
            </label>
            <div>{{ form.born_date }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text">
                <strong>Born location:</strong>
            </label>
            <div>{{ form.born_location }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text">
                <strong>Description:</strong>
            </label>
            <div>{{ form.description }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

quotes_site/app_quotes/templates/app_quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=1.0, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-4">
                <h1>
                    <a href="{% url 'app_quotes:main' %}" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    <li><a class="btn nav-link px-2" href="{% url 'app_quotes:quote' %}">Add new quote</a></li>
                    <li><a class="btn nav-link px-2" href="{% url 'app_quotes:author' %}">Add new author</a></li>
                    
                </ul>
                {% endif %}
            </div>
    
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <span>
                    Welcome <b>{{ user.username }}!</b>
                </span>
                    <a href="{% url 'users:logout' %}">
                        <button type="button" class="btn btn-danger"> Logout</button>
                    </a>
                    
                    {% else %}
                    <a href="{% url 'users:signup' %}">
                        <button type="button" class="btn btn-primary">SignUp</button>
                    </a>
                    <a href="{% url 'users:login' %}">
                        <button type="button" class="btn btn-primary"> Login</button>
                    </a>
                    {% endif %}
                </p>
            </div>
        </div>
        
    

        {% block content %}
        {% endblock %}


        
    <!-- </div>
</div> -->
</div>
</body>
</html>

quotes_site/app_quotes/templates/app_quotes/index.html
{% extends "app_quotes/base.html" %}
<!-- {% load extract %} -->

{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}

    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
            {% endfor %}
                        
        </div>
    </div>

    {% endfor %}

    <nav>       
        <ul class="pager">
            {% if quotes.has_previous %}
            <li class="previous">
                <a href="{% url 'app_quotes:main_paginate' quotes.previous_page_number %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>    
            {% endif %}
            {% if quotes.has_next %}
            <li class="next">
                <a href="{% url 'app_quotes:main_paginate' quotes.next_page_number %}">Next
                    <span aria-hidden="true">→</span>
                </a>
            </li>
            {% endif %}       
        </ul>
    </nav>
    </div>
    
    </div>   
</div>

{% endblock %}

quotes_site/app_quotes/templates/app_quotes/quote.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1 class="text mb-3"> Adding quote</h1>
<form method="POST" action="{% url 'app_quotes:quote' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text">
                <strong>Quote:</strong>
            </label>
            <div>{{ form.quote }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text"><strong>Quote author:</strong></label>
        </div>
         <div class="mb-3 col">
            <select name="author">
                {% for author in all_authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text"><strong>Select tags:</strong></label>
        </div>
        <div class="mb-3 col">
            <select name="tags" class="form-select" size="5">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}