quotes_site/quotes_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_quotes.urls')),
    path('users/', include('users.urls')),
]

quotes_site/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView



from . import views


app_name = "users"

urlpatterns = [
   
    path("signup/", RegisterView.as_view(), name="signup"),
    path("login/", views.login_user, name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
 ]

quotes_site/users/models.py
from django.db import models

# Create your models here.

quotes_site/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms



class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))
    
    first_name = forms.CharField(max_length=100,
                                required=False,
                                widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "First Name"}))
    
    last_name = forms.CharField(max_length=100,
                                required=False,
                                widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Last Name"}))
    
    email = forms.EmailField(max_length=100,
                            required=True,
                            widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "Email"}))
    
    password1 = forms.CharField(max_length=20,
                                required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))
    
    password2 = forms.CharField(max_length=20,
                                required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']




class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))

    password = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))


    class Meta:
        model = User
        fields = ['username', 'password']

quotes_site/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

# Create your views here.

from django.shortcuts import render, redirect
from django.views import View


from .forms import RegisterForm, LoginForm

# Create your views here.

class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_quotes:main")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)



    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class()})
    

    def post(self, request, *args, **kwargs):
        
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f'Ваш акаунт успішно створено: {username}')
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form}) 
    

def login_user(request):
    if request.user.is_authenticated:
        return redirect(to="app_quotes:main")
    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="app_quotes:main")

    return render(request, "users/login.html", context={"form": LoginForm()})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quotes_site/users/templates/users/login.html
{% extends "app_quotes/base.html" %}

{% block content %}
<!--Виводимо Flash сповіщення-->
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<!--обробляємо помилки які не відносяться до полів-->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
  <span>{{ form.non_field_errors }}</span>
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{form.errors.username}}</span>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
        <span>{{form.errors.password}}</span>
    </div>

    <!-- <div class="grid">
        <button type="submit" class="btn btn-primary">Login</button> -->
        <input type="submit" value="Login" class="btn btn-primary">   
    </div>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

quotes_site/users/templates/users/logout.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h1>Thank you!</h1>

{% endblock %}

quotes_site/users/templates/users/password_reset.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes_site/users/templates/users/password_reset_complete.html
{% extends "app_quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes_site/users/templates/users/password_reset_confirm.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes_site/users/templates/users/password_reset_done.html
{% extends "app_quotes/base.html" %}

{% block content %}

<!-- {% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %} -->

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes_site/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes_site/users/templates/users/signup.html
{% extends "app_quotes/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>First Name</label>
                            {{ form.first_name }}
                        </div>
                        <span>{{form.errors.first_name}}</span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Last Name</label>
                            {{ form.last_name }}
                        </div>
                        <span>{{form.errors.last_name}}</span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Username</label>
                            {{ form.username }}
                        </div>
                        <span>{{form.errors.username}}</span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Email</label>
                            {{ form.email }}
                        </div>
                        <span>{{form.errors.email}}</span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Password</label>
                            {{ form.password1 }}
                        </div>
                        <span>{{form.errors.password1}}</span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Confirm password</label>
                            {{ form.password2 }}
                        </div>
                        <span>{{form.errors.password2}}</span>
                    </div>
                </div>
                <div class="form-group mt-4 mb-1">
                    <button type="submit" class="btn btn-success">Sign UP</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}